name: FlagExplorer CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Backend setup
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore backend dependencies
      run: dotnet restore
      
    - name: Build backend
      run: dotnet build --no-restore --configuration Release
      
    - name: Test Backend
      run: |
        cd FlagExplorer.API.Tests
        dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage" --logger trx
      
    # Frontend setup
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install frontend dependencies
      working-directory: ./FlagExplorer.Web
      run: npm install
      
    - name: Build frontend
      working-directory: ./FlagExplorer.Web
      run: npm run build
      
    - name: Test Frontend
      run: |
        cd FlagExplorer.Web.Tests
        dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage" --logger trx
      
    # Publish both
    - name: Publish Backend
      run: dotnet publish ./FlagExplorer.API/FlagExplorer.API.csproj -c Release -o ./publish/api
      
    - name: Publish Frontend
      run: dotnet publish ./FlagExplorer.Web/FlagExplorer.Web.csproj -c Release -o ./publish/web
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-packages
        path: ./publish